---
  - name: build configuration
    hosts: buildapp
    become: yes

    roles:
      - common
      - webserver
      - security
  
  - name: prod config
    hosts: prod
    become: yes

    roles:
      - common
      - security